# Part 1: Introduction to NumPy

## Task 1: Creating Arrays
Create a 1D NumPy array containing the numbers from 1 to 15.

In [172]:
import numpy as np
list1 = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
arr = np.array(list1) # Convert list into NumPy array
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


## Task 2: Reshaping Arrays
Reshape the 1D array from Task 1 into a 3x5 2D array.

In [173]:
arr = arr.reshape(3, 5) # Reshape
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


## Task 3: Basic Arithmetic Operations
Create a new array by adding 2 to every element in the 2D array from Task 2.

In [174]:
new_arr = arr + 2 # Add 2 to each element
print(new_arr)

[[ 3  4  5  6  7]
 [ 8  9 10 11 12]
 [13 14 15 16 17]]


## Task 4: Array Indexing and Slicing
Extract the second row from the 2D array you created in Task 2.

In [175]:
print(arr[1]) # Extraction of second row

[ 6  7  8  9 10]


## Task 5: Element-wise Operations
Multiply each element in the 2D array by 3 and store the result in a new array.

In [176]:
new_array2 = arr * 3 # Multiply by 3
print(new_array2)

[[ 3  6  9 12 15]
 [18 21 24 27 30]
 [33 36 39 42 45]]


## Task 6: Basic Statistics
Calculate the mean and sum of all elements in the array from Task 5.

In [177]:
mean = new_array2.mean() # Calculation of Mean
sum = new_array2.sum() # Calculation of Sum

print(f'Mean: {mean}')
print(f'Sum: {sum}')

Mean: 24.0
Sum: 360


# Part 2: Introduction to Pandas

In [178]:
import pandas as pd

## Task 7: Creating DataFrames
Create a Pandas DataFrame using the following data:

```
 data = {
    'Name': ['Tom', 'Jane', 'Steve'],
    'Age': [28, 34, 29],
    'Salary': [50000, 60000, 55000]
}
```

In [179]:
data = {
    'Name': ['Tom', 'Jane', 'Steve'],
    'Age': [28, 34, 29],
    'Salary': [50000, 60000, 55000]
}

df = pd.DataFrame(data) # Convert dictionary into DataFrame 
print(df)

    Name  Age  Salary
0    Tom   28   50000
1   Jane   34   60000
2  Steve   29   55000


## Task 8: Accessing DataFrame Columns
Select the 'Name' column from the DataFrame and display it.

In [180]:
print(df['Name']) # Displaying of column "Name"

0      Tom
1     Jane
2    Steve
Name: Name, dtype: object


## Task 9: Adding a New Column
Add a new column to the DataFrame called 'Bonus', which is 10% of the 'Salary'.

In [181]:
df.insert(3, 'Bonus', df['Salary'] * 0.1) # Insert with checking of duplicates
print(df)

    Name  Age  Salary   Bonus
0    Tom   28   50000  5000.0
1   Jane   34   60000  6000.0
2  Steve   29   55000  5500.0


## Task 10: Basic DataFrame Statistics
Calculate the average salary of all individuals in the DataFrame.

In [182]:
average = df['Salary'].values.sum() / df['Salary'].count() # Calculation for average salary
print(average)

55000.0
